name: "웹프로그래밍 실습 CI/CD"

on:
    push:
        branches:
            - hjyeeoonng
        # tags:
        #     - release.*

jobs:
    Git-ADD:
        runs-on: ubuntu-latest
        name: "Help_py with CI/CD"
        steps:
          - run: echo "CI/CD실습 프로젝트에 적용하기!"
          - run: 
        name: Checkout Repository
        steps:
          - uses: actions/checkout@v2