name: "웹프로그래밍 실습 CI/CD"

on:
    push:
        branches:
            - hjyeeoonng
        # tags:
        #     - release.*

jobs:
    Git-ADD:
        runs-on: ubuntu-latest
        name: "Help_py with CI/CD"
        steps:
          - run: echo "CI/CD실습 프로젝트에 적용하기!"
          - uses: actions/checkout@v2
          - name: Setup
            uses: actions/setup-node@v4
            with:
              node-version: 18
          - name: cd frontend
            run: |
              ls
              pwd
              cd frontend
              pwd
          - name: cd backend
            run: |
              ls
              pwd
              cd backend
              pwd
          - name: start chat.js
            run: |
              cd backend
              node chat.js