name: "웹프로그래밍 실습 CI/CD"

on:
    push:
        branches:
            - hjyeeoonng
        # tags:
        #     - release.*

jobs:
    Git-ADD:
        runs-on: ubuntu-latest
        name: "변경사항 저장하기"
        steps:
            - run: git add .
            - run: git commit -m "자동 저장"
            - run: git pull origin main
            - run: git push origin hjyeeoonng