name: "김태연 - 웹프로그래밍 실습 CI/CD"

on: 
  push:
    branches: 
      - main
    #tag:
    #  - release.*

jobs:
  taeyeon_kim:
    runs-on: ubuntu-20.04
    steps: 
      - run: echo "${{ github.repository }}"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4 
        with:
          node-version: 18
      - name: "backend로 들어가"
        run: cd backend

      - name: "백엔드 실행해"
        run: |
          cd backend
      
      # 프론트엔드
      - name: "프론트엔드 실행해"
        run: |
          cd frontend
          npm run build
