name: "웹프로그래밍 실습 CI/CD"

on:
  push:
    branches:
      - main
    # tags:
    #     - release.*

jobs:
  Job-Gut-Deul:
    runs-on: ubuntu-latest
    name: "NPM 시작"
    steps:
      - run: echo "happppy ${{ github.repository }}"
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      
      - run: cd backend
      - run: npm i
      - run: node index.js
      - run: cd ../frontend
      - run: npm i
      - run: npm run build
